# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2022-05-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='align',
            field=models.TextField(default='left'),
        ),
    ]
