# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2022-05-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
