# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2022-05-28 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220517_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='userName',
            field=models.TextField(default=datetime.datetime(2022, 5, 28, 13, 17, 53, 800633, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
