# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2022-05-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220529_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.TextField(unique=True),
        ),
    ]
