# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2022-06-02 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20220531_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='userName',
            new_name='userEmail',
        ),
    ]
